/** Primitivas visuales del producto autenticado. */
"use client";

import type { ReactNode } from "react";
import { ApiError } from "@/lib/api";
import type { Tone } from "@/lib/meta";

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: ReactNode; description?: ReactNode; actions?: ReactNode }) {
  return <header className="mb-6 flex flex-col gap-4 border-b border-line pb-5 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0">{eyebrow ? <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-s1">{eyebrow}</p> : null}<h1 className="text-balance text-2xl font-semibold tracking-tight text-ink sm:text-3xl">{title}</h1>{description ? <p className="mt-1 max-w-3xl text-pretty text-sm leading-relaxed text-muted">{description}</p> : null}</div>{actions ? <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div> : null}</header>;
}

export function Card({ title, subtitle, actions, children, className = "" }: { title?: ReactNode; subtitle?: ReactNode; actions?: ReactNode; children: ReactNode; className?: string }) {
  return <section className={`overflow-hidden rounded-2xl border border-line bg-surface-1 shadow-[0_1px_0_rgba(255,255,255,0.025)] ${className}`}>{title || actions ? <header className="flex flex-col gap-3 border-b border-grid px-4 py-4 sm:flex-row sm:items-start sm:justify-between sm:px-5"><div className="min-w-0">{title ? <h2 className="text-balance text-sm font-semibold text-ink">{title}</h2> : null}{subtitle ? <p className="mt-1 text-pretty text-xs leading-relaxed text-muted">{subtitle}</p> : null}</div>{actions ? <div className="flex shrink-0 flex-wrap items-center gap-2">{actions}</div> : null}</header> : null}<div className="p-4 sm:p-5">{children}</div></section>;
}

const TONE_CLASSES: Record<Tone, string> = { good: "bg-good/12 text-good border-good/35", goodTint: "bg-transparent text-good border-good/35", neutral: "bg-surface-2 text-ink-2 border-line", info: "bg-s1/12 text-s1 border-s1/35", warn: "bg-warn/10 text-warn border-warn/35", serious: "bg-serious/10 text-serious border-serious/35", critical: "bg-critical/12 text-critical-text border-critical-text/35" };
export function Badge({ tone = "neutral", children, title }: { tone?: Tone; children: ReactNode; title?: string }) { return <span title={title} className={`inline-flex items-center gap-1 whitespace-nowrap rounded-md border px-2 py-0.5 text-[11px] font-semibold leading-4 ${TONE_CLASSES[tone]}`}>{children}</span>; }
export function ScoreChip({ score, tone }: { score: number | null | undefined; tone: Tone }) { return score == null ? <span className="text-xs text-muted">—</span> : <Badge tone={tone}><span className="num">{score.toFixed(0)}</span><span className="opacity-60">/100</span></Badge>; }

type ButtonVariant = "primary" | "ghost" | "danger";
const BUTTON_CLASSES: Record<ButtonVariant, string> = { primary: "border-s1 bg-s1 text-ink hover:bg-s1/85 disabled:bg-s1/40", ghost: "border-line bg-surface-1 text-ink-2 hover:border-baseline hover:bg-surface-2 hover:text-ink", danger: "border-critical-text/35 bg-transparent text-critical-text hover:bg-critical/10" };
export function Button({ variant = "ghost", size = "md", className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: ButtonVariant; size?: "sm" | "md" }) { const sizeClass = size === "sm" ? "min-h-9 px-3 text-xs" : "min-h-10 px-4 text-sm"; return <button className={`inline-flex items-center justify-center gap-2 rounded-lg border font-semibold transition-colors disabled:cursor-not-allowed disabled:opacity-60 ${sizeClass} ${BUTTON_CLASSES[variant]} ${className}`} {...props} />; }

export function Stat({ label, value, hint, tone }: { label: string; value: ReactNode; hint?: ReactNode; tone?: "up" | "down" | "flat" }) { const valueColor = tone === "up" ? "text-good" : tone === "down" ? "text-critical-text" : "text-ink"; return <div className="relative min-h-32 overflow-hidden rounded-2xl border border-line bg-surface-1 p-4 sm:p-5"><div className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted">{label}</div><div className={`num mt-3 text-2xl font-semibold tracking-tight ${valueColor}`}>{value}</div>{hint ? <div className="mt-1 text-xs leading-relaxed text-muted">{hint}</div> : null}<span className={`absolute inset-x-0 bottom-0 h-0.5 ${tone === "up" ? "bg-good" : tone === "down" ? "bg-critical" : "bg-s1"}`} aria-hidden /></div>; }

export function Spinner({ className = "" }: { className?: string }) { return <span role="status" aria-label="Cargando" className={`inline-block size-4 animate-spin rounded-full border-2 border-baseline border-t-ink-2 ${className}`} />; }
export function Loading({ text = "Cargando…" }: { text?: string }) { return <div className="flex min-h-32 items-center justify-center gap-2 text-sm text-muted" role="status" aria-live="polite"><Spinner /> {text}</div>; }
export function ErrorBox({ error, onRetry }: { error: unknown; onRetry?: () => void }) { const message = error instanceof ApiError ? error.message : error instanceof Error ? error.message : "Error inesperado"; return <div className="flex flex-wrap items-center gap-3 rounded-xl border border-critical-text/30 bg-critical/10 px-4 py-3 text-sm text-critical-text" role="alert"><svg viewBox="0 0 24 24" className="size-4 shrink-0" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden><path d="M12 3L2.5 20h19L12 3z" /><path d="M12 9v5M12 17.5v.5" /></svg><span className="min-w-0 flex-1 leading-relaxed">{message}</span>{onRetry ? <Button size="sm" variant="ghost" onClick={onRetry}>Reintentar</Button> : null}</div>; }
export function EmptyState({ children }: { children: ReactNode }) { return <div className="flex min-h-36 items-center justify-center rounded-xl border border-dashed border-baseline bg-surface-0/40 px-5 py-8 text-center text-sm leading-relaxed text-muted">{children}</div>; }

export function Table({ children }: { children: ReactNode }) { return <div className="-mx-4 overflow-x-auto px-4 sm:-mx-5 sm:px-5"><table className="w-full min-w-max border-separate border-spacing-0 text-left text-sm">{children}</table></div>; }
export function Th({ children, right = false }: { children?: ReactNode; right?: boolean }) { return <th scope="col" className={`sticky top-0 border-b border-baseline bg-surface-1 px-3 py-2.5 text-[10px] font-semibold uppercase tracking-[0.12em] text-muted ${right ? "text-right" : ""}`}>{children}</th>; }
export function Td({ children, right = false, className = "" }: { children?: ReactNode; right?: boolean; className?: string }) { return <td className={`border-b border-grid px-3 py-3 align-middle text-ink-2 ${right ? "num text-right" : ""} ${className}`}>{children}</td>; }
